name: Deploy to GitHub Pages (Simple)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Prepare for deployment
      run: |
        # Copy all files from dist to root for GitHub Pages
        cp -r dist/* ./
        # Remove dist folder from deployment
        rm -rf dist/
        # Remove source files from deployment
        rm -rf src/
        rm -rf node_modules/
        rm -rf .github/
        rm -f package.json package-lock.json gulpfile.js deploy.sh DEPLOYMENT_GUIDE.md
        rm -f .gitignore
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        force_orphan: true
